.TH castle-model-converter 1 "12 May 2013" "Castle Game Engine" "Convert 3D models to VRML / X3D"
.SH NAME
castle-model-converter \- Convert 3D models to X3D, format VRML / X3D to have nice indentation.

.SH SYNOPSIS

.B castle-model-converter
[\fIfile\fR] [\fIoptions...\fR]

.SH DESCRIPTION

.B castle-model-converter
Convert models to X3D, format VRML / X3D to have nice indentation. The output model will be written on standard output.

.SH USAGE

.B castle-model-converter
takes the following arguments:
.TP
.B file
The 3D model file to open.

.TP
.B \-h / \-\-help
Print the help message and exit.

.TP
.B \-v / \-\-version
Print the version number and exit.

.TP
.B \-\-encoding classic|xml
Choose X3D encoding. Default is "classic".

.TP
.B \-\-force\-x3d
Force conversion from VRML to X3D. Note that if you choose XML encoding (by \-\-encoding=xml), this is automatic. Note that this works sensibly only for VRML 2.0 (not for older Inventor/VRML 1.0, we cannot convert them to valid X3D for now).

.SH SEE ALSO
.IP
.BR  castle-model-viewer (1)
