#!/bin/bash
set -eu

# Params: $1 $2 $3 are input filename, output filename (must have PNG
# extension to work, since view3dscene recognizes output file format
# only based on extension, fortunately GNOME passes PNG ext),
# size. So you can just place this as a GNOME thumbnailer with a command
#   view3dscene-thumbnailer %i %o %s
# (hm, it's what everyone uses, but will this handle filenames with spaces?)

view3dscene "$1" --screenshot 0 "$2" --geometry "${3}x${3}"
